### PR TITLE
FlowJumpToDef. Closes #25

### LINKED ISSUE #25: Go to definition
I was wondering if it's possible to implement a feature which allows you to go to the definition of the word under the cursor?

### PR DESCRIPTION
**Pull request by iamdustan**
Closes #25.

### CODE REVIEW

**Comment by mroch** [comment]
i'm a vim n00b. how do you use this?

**Comment by iamdustan** [comment]
@mroch are you on irc or reactiflux?

Assuming you have some sort of vim plugin (Plug, Vundle, etc) and have this whole thing in something like `.vim/autoload/vim-flow` then vim will automatically load it. After that, typing `:FlowJumpToDef` will jump to def for whatever is below the cursor.

I have the following in my `.vimrc` file so that just pressing `gl` will jump to the location.

```vimscript
" .vimrc
map gl :FlowJumpToDef<CR>
```

**Comment by mroch** [comment]
cool, that's what I thought. what's the mark stuff for?

**Comment by iamdustan** [comment]
so that hitting `F or 'F will allow the user to return back to where they came from. Although I’ve been using vim exclusively for 6 years I’m not sure if that is a pattern that is built-in already.

**Comment by iamdustan** [comment]
I can totally remove that stuff, too. Potentially even open the jump-to-def in a split or new tab.

**Comment by mroch** [comment]
the mark stuff sounds good to me. if someone can show a good reason to do something different we can always revisit it. thanks!

**Comment by andreypopp** [comment]
I think mark is unnecessary as Vim allows this with `<C-o>` by default, see: http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations

**Comment by iamdustan** [comment]
Oh nice! Thanks @andreypopp. Do you think it would make more sense to make the JumpToDef opening be configurable between same buffer or new tab?

**Comment by andreypopp** [comment]
@iamdustan I'm happy with jumping within the same tab/window as I'm heavy user of `<C-o>`. By the way, thank you for this feature!

**Pull request merged**
