### PR TITLE
Reorg to use the same flow --from vim command

### PR DESCRIPTION
**Pull request by iamdustan**
Idk what the `--from {editor}` command is *intended* to do, but this reorganization allows for more commands to share in the initial flow startup process and get the `--from vim` command.

The biggest change in here is because the `jump-to-def` format with and without that command changes.

**Output without `--from`:**
`/Users/iamdustan/projects/project/app.js:5:3,5:33`

**Output with `--from vim`:**
 `File "/Users/dkasten/projects/w2g-web/client/root-action-creators.js", line 5, characters 3-33`

### CODE REVIEW

**Comment by mroch** [comment]
as you noticed, `--from vim` and `--from emacs` change the error format into something that vim and emacs have built-in support for.

maintaining special error printers kind of drives me nuts though :) i would love if it was possible for all clients to consume `--json` (#15)

**Comment by iamdustan** [comment]
I’m learning all sorts of vimscripty-ness these past two days :)

I started looking into the `--json` bit. Hope to revisit it soon.

**Comment by mroch** [comment]
maybe the vim-specific format isn't even necessary, since it's got a custom format in `s:flow_errorformat`.

what if you changed s:flow_errorformat to support the standard output (with no `--from`) instead? which format seems easier to parse?

**Comment by mroch** [comment]
i guess you'd probably need `--old-output-format` instead, so that's probably not an improvement... trading one special param for another.

**Pull request merged**
